export const DEFAULT_JOB_SORT_ORDER = [
  3, // MRD 斧术师
  21, // WAR 战士
  1, // GLA 剑术师
  32, // DRK 暗黑骑士
  37, // GNB 绝枪战士
  19, // PLD 骑士
  6, // CNJ 幻术师
  24, // WHM 白魔法师
  33, // AST 占星术士
  40, // SGE 贤者
  28, // SCH 学者
  34, // SAM 武士
  29, // ROG 双剑师
  30, // NIN 忍者
  39, // RPR 钐镰客
  4, // LNC 枪术师
  22, // DRG 龙骑士
  2, // PGL 格斗家
  20, // MNK 武僧
  41, // VPR 蛇武士
  5, // ARC 弓箭手
  23, // BRD 吟游诗人
  31, // MCH 机工士
  38, // DNC 舞者
  7, // THM 咒术师
  25, // BLM 黑魔法师
  26, // ACN 秘术师
  27, // SMN 召唤师
  35, // RDM 赤魔法师
  42, // PCT 绘灵法师
  36, // BLU 青魔法师
  8, // CRP 刻木匠
  9, // BSM 锻铁匠
  10, // ARM 铸甲匠
  11, // GSM 雕金匠
  12, // LTW 制革匠
  13, // WVR 裁衣匠
  14, // ALC 炼金术士
  15, // CUL 烹调师
  16, // MIN 采矿工
  17, // BTN 园艺工
  18, // FSH 捕鱼人
  0, // NONE 冒险者
] as number[];
