import type { Keigenn } from '@/types/keigennRecord2'

const chinese: (Omit<Keigenn, 'fullIcon'> & { fullIcon?: string })[] = [
  {
    name: '铁壁',
    id: 1191,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '盾阵',
    id: 1856,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '干预',
    id: 1174,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '预警',
    id: 74,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '武装',
    id: 1176,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '神圣领域',
    id: 82,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '圣光幕帘',
    id: 1362,
    type: 'absorbed',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '圣盾阵',
    id: 2674,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '骑士的坚守',
    id: 2675,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '壁垒',
    id: 77,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '原初的直觉',
    id: 735,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '原初的勇猛',
    id: 1857,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '原初的武猛',
    id: 1858,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '战栗',
    id: 87,
    type: 'absorbed',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '复仇',
    id: 89,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '摆脱',
    id: 1457,
    type: 'absorbed',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '死斗',
    id: 409,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '原初的血气',
    id: 2678,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '原初的血潮',
    id: 2679,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '原初的血烟',
    id: 2680,
    type: 'absorbed',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '至黑之夜',
    id: 1178,
    type: 'absorbed',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '弃明投暗',
    id: 746,
    type: 'multiplier',
    performance: { physics: 0, magic: 1, darkness: 0 },
    isFriendly: true,
  },
  {
    name: '暗影墙',
    id: 747,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '暗黑布道',
    id: 1894,
    type: 'multiplier',
    performance: { physics: 0, magic: 1, darkness: 0 },
    isFriendly: true,
  },
  {
    name: '行尸走肉',
    id: 810,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '死而不僵',
    id: 811,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '出死入生',
    id: 3255,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '献奉',
    id: 2682,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '石之心',
    id: 1840,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '残暴弹',
    id: 1898,
    type: 'absorbed',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '伪装',
    id: 1832,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '星云',
    id: 1834,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '光之心',
    id: 1839,
    type: 'multiplier',
    performance: { physics: 0, magic: 1, darkness: 0 },
    isFriendly: true,
  },
  {
    name: '超火流星',
    id: 1836,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '刚玉之心',
    id: 2683,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '刚玉之清',
    id: 2684,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '神祝祷',
    id: 1218,
    type: 'absorbed',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '节制',
    id: 1873,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '水流幕',
    id: 2708,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '鼓舞',
    id: 297,
    type: 'absorbed',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '激励',
    id: 1918,
    type: 'absorbed',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '炽天的幕帘',
    id: 1917,
    type: 'absorbed',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '野战治疗阵',
    id: 299,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '异想的幻光',
    id: 317,
    type: 'multiplier',
    performance: { physics: 0, magic: 1, darkness: 0 },
    isFriendly: true,
  },
  {
    name: '炽天的幻光',
    id: 1875,
    type: 'multiplier',
    performance: { physics: 0, magic: 1, darkness: 0 },
    isFriendly: true,
  },
  {
    name: '生命回生法',
    id: 2710,
    type: 'absorbed',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '怒涛之计',
    id: 2711,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '命运之轮',
    id: 849,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '天星交错',
    id: 1889,
    type: 'absorbed',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '擢升',
    id: 2717,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '中间学派',
    id: 1921,
    type: 'absorbed',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '均衡诊断',
    id: 2607,
    type: 'absorbed',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '齐衡诊断',
    id: 2608,
    type: 'absorbed',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '均衡预后',
    id: 2609,
    type: 'absorbed',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '坚角清汁',
    id: 2618,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '白牛清汁',
    id: 2619,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '整体论',
    id: 3003,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '整体盾',
    id: 3365,
    type: 'absorbed',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '输血',
    id: 2612,
    type: 'absorbed',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '泛输血',
    id: 2613,
    type: 'absorbed',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '心眼',
    id: 1232,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '金刚极意',
    id: 1179,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '行吟',
    id: 1934,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '策动',
    id: 1951,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '防守之桑巴',
    id: 1826,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '即兴表演结束',
    id: 2697,
    type: 'absorbed',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '残影',
    id: 488,
    type: 'absorbed',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '魔罩',
    id: 168,
    type: 'absorbed',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '守护之光',
    id: 2702,
    type: 'absorbed',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '守护纹',
    id: 2597,
    type: 'absorbed',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '抗死',
    id: 2707,
    type: 'multiplier',
    performance: { physics: 0, magic: 1, darkness: 0 },
    isFriendly: true,
  },
  {
    name: '雪仇',
    id: 1193,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: false,
  },
  {
    name: '牵制',
    id: 1195,
    type: 'multiplier',
    performance: { physics: 1, magic: 0.5, darkness: 0 },
    isFriendly: false,
  },
  {
    name: '昏乱',
    id: 1203,
    type: 'multiplier',
    performance: { physics: 0.5, magic: 1, darkness: 0 },
    isFriendly: false,
  },
  {
    name: '武装解除',
    id: 860,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: false,
  },
  {
    name: '减速',
    id: 9,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: false,
  },
  {
    name: '体力增加',
    id: 2120,
    type: 'absorbed',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '腐臭',
    id: 1715,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: false,
  },
  {
    name: '智力精神降低',
    id: 2115,
    type: 'multiplier',
    performance: { physics: 0, magic: 1, darkness: 0 },
    isFriendly: false,
  },
  {
    name: '龙之力',
    id: 2500,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '超硬化',
    id: 1722,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '玄结界',
    id: 2496,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '仙人盾',
    id: 2119,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '强力守护',
    id: 1719,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '哥布防御',
    id: 2114,
    type: 'absorbed',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '铜墙铁盾',
    id: 194,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '坚守要塞',
    id: 195,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '终极堡垒',
    id: 196,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '原初大地',
    id: 863,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '暗黑之力',
    id: 864,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '灵魂之青',
    id: 1931,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '极致防御',
    id: 3829,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '极致护盾',
    id: 3830,
    type: 'absorbed',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '戮罪',
    id: 3832,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '暗影卫',
    id: 3835,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '大星云',
    id: 3838,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '坦培拉涂层',
    id: 3686,
    type: 'absorbed',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '油性坦培拉涂层',
    id: 3687,
    type: 'absorbed',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '世界树之干',
    id: 3890,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '建筑神之塔',
    id: 3892,
    type: 'absorbed',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '太阳星座',
    id: 3896,
    type: 'multiplier',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: '神爱抚',
    id: 3903,
    type: 'absorbed',
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
]
const global: typeof chinese = [...chinese]

export { chinese, global }
