import type { Keigenn } from "@/types/keigennRecord2";

const keigenns: (Omit<Keigenn, "fullIcon"> & { fullIcon?: string })[] = [
  {
    // 深层迷宫版本
    name: "受伤减轻",
    id: 0x44c,
    type: "multiplier",
    performance: { physics: 0.6, magic: 0.6, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "铁壁",
    id: 1191,
    type: "multiplier",
    performance: { physics: 0.8, magic: 0.8, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "盾阵",
    id: 1856,
    type: "multiplier",
    performance: { physics: 0.85, magic: 0.85, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "干预",
    id: 1174,
    type: "multiplier",
    performance: { physics: 0.9, magic: 0.9, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "预警",
    id: 74,
    type: "multiplier",
    performance: { physics: 0.7, magic: 0.7, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "武装",
    id: 1176,
    type: "multiplier",
    performance: { physics: 0.85, magic: 0.85, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "神圣领域",
    id: 82,
    type: "multiplier",
    performance: { physics: 0, magic: 0, darkness: 0 },
    isFriendly: true,
  },
  {
    name: "圣光幕帘",
    id: 1362,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "圣盾阵",
    id: 2674,
    type: "multiplier",
    performance: { physics: 0.85, magic: 0.85, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "骑士的坚守",
    id: 2675,
    type: "multiplier",
    performance: { physics: 0.9, magic: 0.9, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "壁垒",
    id: 77,
    type: "multiplier",
    // 不用写，因为到时候会取格挡
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "极致防御",
    id: 3829,
    type: "multiplier",
    performance: { physics: 0.6, magic: 0.6, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "极致护盾",
    id: 3830,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "原初的直觉",
    id: 735,
    type: "multiplier",
    performance: { physics: 0.9, magic: 0.9, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "原初的勇猛",
    id: 1857,
    type: "multiplier",
    performance: { physics: 0.9, magic: 0.9, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "原初的武猛",
    id: 1858,
    type: "multiplier",
    performance: { physics: 0.9, magic: 0.9, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "战栗",
    id: 87,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "复仇",
    id: 89,
    type: "multiplier",
    performance: { physics: 0.7, magic: 0.7, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "摆脱",
    id: 1457,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "死斗",
    id: 409,
    type: "multiplier",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "原初的血气",
    id: 2678,
    type: "multiplier",
    performance: { physics: 0.9, magic: 0.9, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "原初的血潮",
    id: 2679,
    type: "multiplier",
    performance: { physics: 0.9, magic: 0.9, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "原初的血烟",
    id: 2680,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "戮罪",
    id: 3832,
    type: "multiplier",
    performance: { physics: 0.6, magic: 0.6, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "至黑之夜",
    id: 1178,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "弃明投暗",
    id: 746,
    type: "multiplier",
    performance: { physics: 0.9, magic: 0.8, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "暗影墙",
    id: 747,
    type: "multiplier",
    performance: { physics: 0.7, magic: 0.7, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "暗黑布道",
    id: 1894,
    type: "multiplier",
    performance: { physics: 0.95, magic: 0.9, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "暗影卫",
    id: 3835,
    type: "multiplier",
    performance: { physics: 0.6, magic: 0.6, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "行尸走肉",
    id: 810,
    type: "multiplier",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "死而不僵",
    id: 811,
    type: "multiplier",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "出死入生",
    id: 3255,
    type: "multiplier",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "献奉",
    id: 2682,
    type: "multiplier",
    performance: { physics: 0.9, magic: 0.9, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "石之心",
    id: 1840,
    type: "multiplier",
    performance: { physics: 0.85, magic: 0.85, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "残暴弹",
    id: 1898,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "伪装",
    id: 1832,
    type: "multiplier",
    performance: { physics: 0.9, magic: 0.9, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "星云",
    id: 1834,
    type: "multiplier",
    performance: { physics: 0.7, magic: 0.7, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "光之心",
    id: 1839,
    type: "multiplier",
    performance: { physics: 0.95, magic: 0.9, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "超火流星",
    id: 1836,
    type: "multiplier",
    performance: { physics: 0, magic: 0, darkness: 0 },
    isFriendly: true,
  },
  {
    name: "刚玉之心",
    id: 2683,
    type: "multiplier",
    performance: { physics: 0.85, magic: 0.85, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "刚玉之清",
    id: 2684,
    type: "multiplier",
    performance: { physics: 0.85, magic: 0.85, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "神祝祷",
    id: 1218,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "告解", // 全大赦
    id: 1219,
    type: "multiplier",
    performance: { physics: 0.9, magic: 0.9, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "节制",
    id: 1873,
    type: "multiplier",
    performance: { physics: 0.9, magic: 0.9, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "水流幕",
    id: 2708,
    type: "multiplier",
    performance: { physics: 0.85, magic: 0.85, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "鼓舞",
    id: 297,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "激励",
    id: 1918,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "炽天的幕帘",
    id: 1917,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "野战治疗阵",
    id: 299,
    type: "multiplier",
    performance: { physics: 0.9, magic: 0.9, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "异想的幻光",
    id: 317,
    type: "multiplier",
    performance: { physics: 1, magic: 0.95, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "炽天的幻光",
    id: 1875,
    type: "multiplier",
    performance: { physics: 1, magic: 0.95, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "生命回生法",
    id: 2710,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "怒涛之计",
    id: 2711,
    type: "multiplier",
    performance: { physics: 0.9, magic: 0.9, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "命运之轮",
    id: 849,
    type: "multiplier",
    performance: { physics: 0.9, magic: 0.9, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "天星交错",
    id: 1889,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "擢升",
    id: 2717,
    type: "multiplier",
    performance: { physics: 0.9, magic: 0.9, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "中间学派",
    id: 1921,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "均衡诊断",
    id: 2607,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "齐衡诊断",
    id: 2608,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "均衡预后",
    id: 2609,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "坚角清汁",
    id: 2618,
    type: "multiplier",
    performance: { physics: 0.9, magic: 0.9, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "白牛清汁",
    id: 2619,
    type: "multiplier",
    performance: { physics: 0.9, magic: 0.9, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "整体论",
    id: 3003,
    type: "multiplier",
    performance: { physics: 0.9, magic: 0.9, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "整体盾",
    id: 3365,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "输血",
    id: 2612,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "泛输血",
    id: 2613,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "心眼",
    id: 1232,
    type: "multiplier",
    performance: { physics: 0.9, magic: 0.9, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "金刚极意",
    id: 1179,
    type: "multiplier",
    performance: { physics: 0.8, magic: 0.8, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "行吟",
    id: 1934,
    type: "multiplier",
    performance: { physics: 0.85, magic: 0.85, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "策动",
    id: 1951,
    type: "multiplier",
    performance: { physics: 0.85, magic: 0.85, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "防守之桑巴",
    id: 1826,
    type: "multiplier",
    performance: { physics: 0.85, magic: 0.85, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "即兴表演结束",
    id: 2697,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "残影",
    id: 488,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "魔罩",
    id: 168,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "守护之光",
    id: 2702,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "守护纹",
    id: 2597,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "抗死",
    id: 2707,
    type: "multiplier",
    performance: { physics: 1, magic: 0.9, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "雪仇",
    id: 1193,
    type: "multiplier",
    performance: { physics: 0.9, magic: 0.9, darkness: 1 },
    isFriendly: false,
  },
  {
    name: "牵制",
    id: 1195,
    type: "multiplier",
    performance: { physics: 0.9, magic: 0.95, darkness: 1 },
    isFriendly: false,
  },
  {
    name: "昏乱",
    id: 1203,
    type: "multiplier",
    performance: { physics: 0.95, magic: 0.9, darkness: 1 },
    isFriendly: false,
  },
  {
    name: "武装解除",
    id: 860,
    type: "multiplier",
    performance: { physics: 0.9, magic: 0.9, darkness: 1 },
    isFriendly: false,
  },
  {
    name: "减速",
    id: 9,
    type: "multiplier",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: false,
  },
  {
    name: "体力增加",
    id: 2120,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    // 臭气
    name: "腐臭",
    id: 1715,
    type: "multiplier",
    performance: { physics: 0.9, magic: 0.9, darkness: 1 },
    isFriendly: false,
  },
  {
    // 魔法锤
    name: "智力精神降低",
    id: 2115,
    type: "multiplier",
    performance: { physics: 1, magic: 0.9, darkness: 1 },
    isFriendly: false,
  },
  {
    // 常态20%，T青40%，统一按T算。
    name: "龙之力",
    id: 2500,
    type: "multiplier",
    performance: { physics: 0.6, magic: 0.6, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "超硬化",
    id: 1722,
    type: "multiplier",
    performance: { physics: 0.1, magic: 0.1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "玄结界",
    id: 2496,
    type: "multiplier",
    performance: { physics: 0.8, magic: 0.8, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "仙人盾",
    id: 2119,
    type: "multiplier",
    performance: { physics: 0.95, magic: 0.95, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "强力守护",
    id: 1719,
    type: "multiplier",
    performance: { physics: 0.6, magic: 0.6, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "哥布防御",
    id: 2114,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "铜墙铁盾",
    id: 194,
    type: "multiplier",
    performance: { physics: 0.8, magic: 0.8, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "坚守要塞",
    id: 195,
    type: "multiplier",
    performance: { physics: 0.6, magic: 0.6, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "终极堡垒",
    id: 196,
    type: "multiplier",
    performance: { physics: 0.2, magic: 0.2, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "原初大地",
    id: 863,
    type: "multiplier",
    performance: { physics: 0.2, magic: 0.2, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "暗黑之力",
    id: 864,
    type: "multiplier",
    performance: { physics: 0.2, magic: 0.2, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "灵魂之青",
    id: 1931,
    type: "multiplier",
    performance: { physics: 0.2, magic: 0.2, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "坦培拉涂层",
    id: 3686,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "油性坦培拉涂层",
    id: 3687,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "世界树之干",
    id: 3890,
    type: "multiplier",
    performance: { physics: 0.9, magic: 0.9, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "建筑神之塔",
    id: 3892,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "太阳星座",
    id: 3896,
    type: "multiplier",
    performance: { physics: 0.9, magic: 0.9, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "神爱抚",
    id: 3903,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },

  // #region PvP

  // * 防护职业
  {
    name: "防御",
    id: 3054,
    type: "multiplier",
    performance: { physics: 0.1, magic: 0.1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "弱化防御",
    id: 3673,
    type: "multiplier",
    performance: { physics: 0.55, magic: 0.55, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "无法防御",
    id: 3021,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "强盾猛击",
    id: 4283,
    type: "multiplier",
    performance: { physics: 1.1, magic: 1.1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "圣盾阵",
    id: 3026,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "忠义之盾",
    id: 3188,
    type: "multiplier",
    performance: { physics: 0.85, magic: 0.85, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "列阵",
    id: 3210,
    type: "multiplier",
    performance: { physics: 0.67, magic: 0.67, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "神圣领域",
    id: 1302,
    type: "multiplier",
    performance: { physics: 0, magic: 0, darkness: 0 },
    isFriendly: true,
  },
  {
    name: "暴怒",
    id: 4476,
    type: "multiplier",
    performance: { physics: 1.25, magic: 1.25, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "铁壁",
    id: 1978,
    type: "multiplier",
    performance: { physics: 0.5, magic: 0.5, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "猛攻",
    id: 3029,
    type: "multiplier",
    performance: { physics: 1.1, magic: 1.1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "原初的血烟",
    id: 3031,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "至黑之夜",
    id: 1308,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "不死救赎",
    id: 3039,
    type: "multiplier",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "刚玉之心",
    id: 4295,
    type: "multiplier",
    performance: { physics: 0.9, magic: 0.9, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "超高速",
    id: 3047,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "命运之印",
    id: 4294,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "撕喉",
    id: 3048,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "裂膛",
    id: 3049,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "穿目",
    id: 3050,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "连续剑伤",
    id: 3053,
    type: "multiplier",
    performance: { physics: 1.05, magic: 1.05, darkness: 1 },
    isFriendly: true,
  },

  // * 治疗职业
  {
    name: "坚石肤",
    id: 4481,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "水流幕",
    id: 3086,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "自然的奇迹",
    id: 3085,
    type: "multiplier",
    performance: { physics: 1.2, magic: 1.2, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "护盾",
    id: 1415,
    type: "multiplier",
    performance: { physics: 0.9, magic: 0.9, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "鼓舞",
    id: 3081,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "激励",
    id: 3088,
    type: "multiplier",
    performance: { physics: 0.9, magic: 0.9, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "连环计",
    id: 1406,
    type: "multiplier",
    performance: { physics: 1.1, magic: 1.1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "炽天的幕帘",
    id: 3097,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "慰藉",
    id: 3098,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "吉星相位（夜）",
    id: 3100,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "本轮",
    id: 4330,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "王冠之贵妇",
    id: 1452,
    type: "multiplier",
    performance: { physics: 0.9, magic: 0.9, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "王冠之领主",
    id: 1452,
    type: "multiplier",
    performance: { physics: 1.1, magic: 1.1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "输血",
    id: 3110,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "血印",
    id: 3111,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "箭毒",
    id: 3113,
    type: "multiplier",
    performance: { physics: 1.1, magic: 1.1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "均衡诊断",
    id: 3109,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "中庸之道",
    id: 3119,
    type: "multiplier",
    performance: { physics: 0, magic: 0, darkness: 0 },
    isFriendly: true,
  },

  // * 近战DPS
  {
    name: "轻身步法",
    id: 3173,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "红莲龙血",
    id: 3177,
    type: "multiplier",
    performance: { physics: 1.15, magic: 1.15, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "天穹破碎",
    id: 3181,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "残影",
    id: 2011,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "风遁之术",
    id: 3186,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "土遁之术",
    id: 4304,
    type: "multiplier",
    performance: { physics: 0.85, magic: 0.85, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "必杀剑·地天",
    id: 1240,
    type: "multiplier",
    performance: { physics: 0.67, magic: 0.67, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "奥义斩浪",
    id: 3199,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "回返斩浪",
    id: 3200,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "守护纹",
    id: 2861,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "恐慌",
    id: 3023,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "蛇鳞",
    id: 4096,
    type: "multiplier",
    performance: { physics: 0.5, magic: 0.5, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "蛇鳞甲",
    id: 4097,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },

  // * 远敏DPS
  {
    name: "勇气",
    id: 4479,
    type: "multiplier",
    performance: { physics: 0.75, magic: 0.75, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "光阴神的庇护",
    id: 2178,
    type: "multiplier",
    performance: { physics: 0.75, magic: 0.75, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "扇舞",
    id: 2052,
    type: "multiplier",
    performance: { physics: 0.8, magic: 0.8, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "刃舞",
    id: 3162,
    type: "multiplier",
    performance: { physics: 0.75, magic: 0.75, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "刃舞·终",
    id: 3164,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "诱惑",
    id: 3024,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },

  // * 法系DPS
  {
    name: "幻影弹",
    id: 1986,
    type: "multiplier",
    performance: { physics: 1.25, magic: 1.25, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "磁暴",
    id: 3221,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "寒冰环",
    id: 4316,
    type: "multiplier",
    performance: { physics: 0.8, magic: 0.8, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "守护之光",
    id: 3224,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "魔回刺",
    id: 3234,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "魔交击斩",
    id: 3235,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "魔连攻",
    id: 3236,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "鼓励",
    id: 2282,
    type: "multiplier",
    performance: { physics: 0.92, magic: 0.92, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "剑身强部",
    id: 4320,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "兽爪构想",
    id: 4111,
    type: "multiplier",
    performance: { physics: 1.1, magic: 1.1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "坦培拉涂层",
    id: 4114,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "油性坦培拉涂层",
    id: 4115,
    type: "absorbed",
    performance: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "胖胖之壁",
    id: 4117,
    type: "multiplier",
    performance: { physics: 0.75, magic: 0.75, darkness: 1 },
    isFriendly: true,
  },

  // #endregion
];
export { keigenns };
