type EnemyData = {
  grade?: '简单' | '中等' | '困难' | '危险' | '小心'
  detect?: '视觉' | '听觉' | '范围'
  note?: string
}

type EnemyDataRecord = Record<number, EnemyData | undefined>

const PtEnemies: EnemyDataRecord = {
  // 通用
  14267: { grade: '小心', note: '亡语：眩晕周围' }, // '漫步科柯瑞甘'
  14265: { grade: '小心', note: '尽快击杀，打断怨念' }, // '拟态怪'

  // 1-10层
  14101: { grade: undefined, detect: undefined, note: '' }, // '漫步石莲猬'
  14110: { grade: undefined, detect: undefined, note: '' }, // '漫步灌木丛'
  14102: { grade: undefined, detect: undefined, note: '' }, // '漫步普卡精'
  14100: { grade: undefined, detect: undefined, note: '' }, // '漫步紫闪蝶'
  14103: { grade: undefined, detect: undefined, note: '' }, // '漫步鹰蜓'
  14111: { grade: undefined, detect: undefined, note: '' }, // '漫步吸蜜鹦鹉'
  14104: { grade: undefined, detect: undefined, note: '' }, // '漫步苔菇'
  14105: { grade: undefined, detect: undefined, note: '' }, // '漫步花楸'
  14107: { grade: undefined, detect: undefined, note: '' }, // '漫步铁线莲'
  14106: { grade: undefined, detect: undefined, note: '' }, // '漫步杀人蜂'
  14108: { grade: undefined, detect: undefined, note: '' }, // '漫步篮子'
  14112: { grade: undefined, detect: undefined, note: '' }, // '漫步玫瑰熊'
  14109: { grade: undefined, detect: undefined, note: '' }, // '漫步爱蒂恩蛾'

  // 11-20层
  14117: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的暴力'
  14115: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的蠢笨'
  14113: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的盲从'
  13973: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的模仿'
  14119: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的欺骗'
  14120: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的轻蔑'
  14118: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的违命'
  14114: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的无知'
  14116: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的自负'
  14121: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的自满'
  14123: { grade: undefined, detect: undefined, note: '' }, // '漫步灌木塑像'
  14122: { grade: undefined, detect: undefined, note: '' }, // '漫步帕克'
  14124: { grade: undefined, detect: undefined, note: '' }, // '漫步豌豆花'
  14125: { grade: undefined, detect: undefined, note: '' }, // '漫步幼体龙鸟'

  // 21-30层
  13863: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的叛逆'
  14126: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的妒忌'
  14127: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的情欲'
  14128: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的失调'
  14129: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的残忍'
  14130: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的奢望'
  14131: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的侮辱'
  14132: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的踌躇'
  14133: { grade: undefined, detect: undefined, note: '' }, // '漫步石像'
  14134: { grade: undefined, detect: undefined, note: '' }, // '漫步莫高海怪'
  14135: { grade: undefined, detect: undefined, note: '' }, // '漫步角雉'
  14136: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的贿赂'
  14137: { grade: undefined, detect: undefined, note: '' }, // '漫步冰海天使'
  14138: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的不容忍'

  // 31-40层
  13977: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的纯真'
  13978: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的奉承'
  14139: { grade: undefined, detect: undefined, note: '' }, // '漫步石兵'
  14140: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的瘟疫'
  14141: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的堕落'
  14142: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的勒索'
  14143: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的偏见'
  14144: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的伪善'
  14145: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的任性'
  14146: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的嘲弄'
  14147: { grade: undefined, detect: undefined, note: '' }, // '漫步异端审问官'
  14148: { grade: undefined, detect: undefined, note: '' }, // '漫步鸟'
  14149: { grade: undefined, detect: undefined, note: '' }, // '漫步石狮'
  14150: { grade: undefined, detect: undefined, note: '' }, // '漫步亚克鲁斯'
  14151: { grade: undefined, detect: undefined, note: '' }, // '漫步飞马'

  // 41-50层
  14152: { grade: undefined, detect: undefined, note: '' }, // '漫步替身'
  14153: { grade: undefined, detect: undefined, note: '' }, // '漫步托尔巴龟'
  14154: { grade: undefined, detect: undefined, note: '' }, // '漫步水蚺'
  14155: { grade: undefined, detect: undefined, note: '' }, // '漫步三裂'
  14156: { grade: undefined, detect: undefined, note: '' }, // '漫步蜥蜴'
  14157: { grade: undefined, detect: undefined, note: '' }, // '漫步白蚁'
  14158: { grade: undefined, detect: undefined, note: '' }, // '漫步蚁狮'
  14159: { grade: undefined, detect: undefined, note: '' }, // '漫步钳嘴鸟'
  14160: { grade: undefined, detect: undefined, note: '' }, // '漫步壁崖飞鸢'
  14161: { grade: undefined, detect: undefined, note: '' }, // '漫步武器'
  14162: { grade: undefined, detect: undefined, note: '' }, // '漫步龙舌兰'
  14163: { grade: undefined, detect: undefined, note: '' }, // '漫步发芽大口花'
  14164: { grade: undefined, detect: undefined, note: '' }, // '漫步螳螂'
  14263: { grade: undefined, detect: undefined, note: '' }, // '奥古布纳巴里'

  // 51-60层
  14097: { grade: undefined, detect: undefined, note: '' }, // '元祖马利克刺人仙'
  14098: { grade: undefined, detect: undefined, note: '' }, // '埃米尔仙人刺'
  14099: { grade: undefined, detect: undefined, note: '' }, // '艾米拉仙人花'
  14165: { grade: undefined, detect: undefined, note: '' }, // '漫步褐爪'
  14166: { grade: undefined, detect: undefined, note: '' }, // '漫步守护者'
  14167: { grade: undefined, detect: undefined, note: '' }, // '漫步沙蛇'
  14168: { grade: undefined, detect: undefined, note: '' }, // '漫步美甲兽'
  14169: { grade: undefined, detect: undefined, note: '' }, // '漫步巨蜥'
  14170: { grade: undefined, detect: undefined, note: '' }, // '漫步邪恶海鸟'
  14171: { grade: undefined, detect: undefined, note: '' }, // '漫步帕查玛玛'
  14172: { grade: undefined, detect: undefined, note: '' }, // '漫步神香草'
  14173: { grade: undefined, detect: undefined, note: '' }, // '漫步恐鹤'
  14174: { grade: undefined, detect: undefined, note: '' }, // '漫步吼叫的小豹'
  14175: { grade: undefined, detect: undefined, note: '' }, // '漫步狞猫'
  14176: { grade: undefined, detect: undefined, note: '' }, // '漫步巨人'
  14177: { grade: undefined, detect: undefined, note: '' }, // '漫步甲虫'

  // 61-70层
  14182: { grade: undefined, detect: undefined, note: '' }, // '漫步塔罗斯'
  14187: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的疑虑'
  14183: { grade: undefined, detect: undefined, note: '' }, // '漫步壁崖鼹鼠'
  14189: { grade: undefined, detect: undefined, note: '' }, // '漫步诺姆'
  14178: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的暴动'
  14185: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的恶作剧'
  14184: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的偏颇'
  14180: { grade: undefined, detect: undefined, note: '' }, // '漫步蜂后'
  14181: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的怨恨'
  14188: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的眷恋'
  14179: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的争论'
  14186: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的贪食'
  14190: { grade: undefined, detect: undefined, note: '' }, // '漫步恩戈齐'
  13971: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的狂热'
  // 71-80层
  14195: { grade: undefined, detect: undefined, note: '' }, // '漫步爆岩怪'
  14196: { grade: undefined, detect: undefined, note: '' }, // '漫步奶油泡芙'
  14203: { grade: undefined, detect: undefined, note: '' }, // '漫步铰颌蚁'
  14200: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的不信任'
  14194: { grade: undefined, detect: undefined, note: '' }, // '漫步食岩者'
  14193: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的恶意'
  14198: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的傲慢'
  14202: { grade: undefined, detect: undefined, note: '' }, // '漫步蠕虫'
  14191: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的不和'
  14201: { grade: undefined, detect: undefined, note: '' }, // '漫步阿米特'
  14192: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的腐化物'
  14197: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的虚夸'
  14199: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的诽谤'
  13968: { grade: undefined, detect: undefined, note: '' }, // '得到宽恕的亵渎'

  // 81-90层
  14210: { grade: undefined, detect: undefined, note: '' }, // '漫步异豺'
  14209: { grade: undefined, detect: undefined, note: '' }, // '被召唤的格雷姆林'
  14206: { grade: undefined, detect: undefined, note: '' }, // '漫步骑士'
  14211: { grade: undefined, detect: undefined, note: '' }, // '漫步卡部斯'
  14212: { grade: undefined, detect: undefined, note: '' }, // '被召唤的小撒旦'
  14204: { grade: undefined, detect: undefined, note: '' }, // '漫步卡马'
  14207: { grade: undefined, detect: undefined, note: '' }, // '被召唤的梦魔'
  14213: { grade: undefined, detect: undefined, note: '' }, // '被召唤的上级恶魔'
  14214: { grade: undefined, detect: undefined, note: '' }, // '被召唤的盖因'
  14216: { grade: undefined, detect: undefined, note: '' }, // '被召唤的行吟诗人'
  14205: { grade: undefined, detect: undefined, note: '' }, // '被召唤的巴力'
  14208: { grade: undefined, detect: undefined, note: '' }, // '被召唤的洪巴巴'
  14215: { grade: undefined, detect: undefined, note: '' }, // '被召唤的刻耳柏洛斯'
  14090: { grade: undefined, detect: undefined, note: '' }, // '玛拉科达'

  // 91-100层
  14219: { grade: undefined, detect: undefined, note: '' }, // '被召唤的梦祸'
  14223: { grade: undefined, detect: undefined, note: '' }, // '漫步紫三裂'
  14224: { grade: undefined, detect: undefined, note: '' }, // '漫步食人花'
  14227: { grade: undefined, detect: undefined, note: '' }, // '被召唤的傀儡'
  14225: { grade: undefined, detect: undefined, note: '' }, // '被召唤的扎哈克'
  14217: { grade: undefined, detect: undefined, note: '' }, // '漫步狼人'
  14222: { grade: undefined, detect: undefined, note: '' }, // '被召唤的锯齿花'
  14220: { grade: undefined, detect: undefined, note: '' }, // '被召唤的单身汉'
  14229: { grade: undefined, detect: undefined, note: '' }, // '被召唤的古恶魔'
  14228: { grade: undefined, detect: undefined, note: '' }, // '漫步恶念'
  14221: { grade: undefined, detect: undefined, note: '' }, // '被召唤的破坏本能'
  14226: { grade: undefined, detect: undefined, note: '' }, // '被召唤的阿刻戎'
  14218: { grade: undefined, detect: undefined, note: '' }, // '被召唤的古辛'
  14037: { grade: undefined, detect: undefined, note: '' }, // '至极悲痛'
  14038: { grade: undefined, detect: undefined, note: '' }, // '被侵蚀的食罪灵'
} as const

export { PtEnemies, type EnemyData }
