type EnemyData = {
  grade?: '简单' | '中等' | '困难' | '危险' | '小心'
  detect?: '视觉' | '听觉' | '范围'
  note?: string
}

type EnemyDataRecord = Record<number, EnemyData | undefined>

const PtEnemies: EnemyDataRecord = {
  // 通用
  14265: { grade: '小心', note: '尽快击杀，打断怨念' }, // '拟态怪'
  14267: { grade: '小心', note: '亡语：眩晕周围' }, // '漫步科柯瑞甘'

  // 1-10层
  14100: { detect: '视觉', grade: '简单', note: '无' }, // '漫步紫闪蝶'
  14101: { detect: '视觉', grade: '简单', note: '无' }, // '漫步石莲猬'
  14102: { detect: '视觉', grade: '简单', note: '无' }, // '漫步普卡精'
  14103: { detect: '视觉', grade: '简单', note: '无' }, // '漫步鹰蜓'
  14104: { detect: '听觉', grade: '简单', note: '无' }, // '漫步苔菇'
  14105: { detect: '视觉', grade: '简单', note: '无' }, // '漫步花楸'
  14106: { detect: '视觉', grade: '简单', note: '无' }, // '漫步杀人蜂'
  14107: { detect: '听觉', grade: '简单', note: '无' }, // '漫步铁线莲'
  14108: { detect: '视觉', grade: '简单', note: '无' }, // '漫步篮子'
  14109: { detect: '视觉', grade: '简单', note: '无' }, // '漫步爱蒂恩蛾'
  14110: { detect: '视觉', grade: '简单', note: '巡逻怪' }, // '漫步灌木丛'
  14111: { detect: '视觉', grade: '简单', note: '巡逻怪' }, // '漫步吸蜜鹦鹉'
  14112: { detect: '听觉', grade: '简单', note: '巡逻怪' }, // '漫步玫瑰熊'
  13979: { detect: '视觉', grade: '小心', note: '10层BOSS：召唤小怪，会复制BOSS的技能，可选中后尽快击杀。BOSS还会释放捕食，记好预兆寻找安全区。' }, // '花人' 10层BOSS

  // 11-20层
  13973: { detect: undefined, grade: undefined, note: undefined }, // '得到宽恕的模仿'
  14113: { detect: undefined, grade: undefined, note: undefined }, // '得到宽恕的盲从'
  14114: { detect: undefined, grade: undefined, note: undefined }, // '得到宽恕的无知'
  14115: { detect: undefined, grade: undefined, note: undefined }, // '得到宽恕的蠢笨'
  14116: { detect: undefined, grade: undefined, note: undefined }, // '得到宽恕的自负'
  14117: { detect: undefined, grade: undefined, note: undefined }, // '得到宽恕的暴力'
  14118: { detect: undefined, grade: undefined, note: undefined }, // '得到宽恕的违命'
  14119: { detect: undefined, grade: undefined, note: undefined }, // '得到宽恕的欺骗'
  14120: { detect: undefined, grade: undefined, note: undefined }, // '得到宽恕的轻蔑'
  14121: { detect: undefined, grade: undefined, note: undefined }, // '得到宽恕的自满'
  14122: { detect: undefined, grade: undefined, note: undefined }, // '漫步帕克'
  14123: { detect: undefined, grade: undefined, note: undefined }, // '漫步灌木塑像'
  14124: { detect: undefined, grade: undefined, note: undefined }, // '漫步豌豆花'
  14125: { detect: undefined, grade: undefined, note: undefined }, // '漫步幼体龙鸟'

  // 21-30层
  13863: { detect: undefined, grade: undefined, note: undefined }, // '得到宽恕的叛逆'
  14126: { detect: '视觉', grade: '简单', note: '巡逻怪' }, // '得到宽恕的妒忌'
  14127: { detect: '视觉', grade: '简单', note: '非战斗状态下会读条玩家脚底黄圈' }, // '得到宽恕的情欲'
  14128: { detect: undefined, grade: undefined, note: '巡逻怪' }, // '得到宽恕的失调'
  14129: { detect: '视觉', grade: '简单', note: undefined }, // '得到宽恕的残忍'
  14130: { detect: '视觉', grade: '小心', note: '读条扇形顺劈' }, // '得到宽恕的奢望'
  14131: { detect: '视觉', grade: '简单', note: undefined }, // '得到宽恕的侮辱'
  14132: { detect: '视觉', grade: '简单', note: undefined }, // '得到宽恕的踌躇'
  14133: { detect: '视觉', grade: '简单', note: '读条玩家脚底钢铁' }, // '漫步石像'
  14134: { detect: '视觉', grade: '简单', note: undefined }, // '漫步莫高海怪'
  14135: { detect: '视觉', grade: '简单', note: undefined }, // '漫步角雉'
  14136: { detect: undefined, grade: undefined, note: undefined }, // '得到宽恕的贿赂'
  14137: { detect: '视觉', grade: '小心', note: '在血量<25%后，会读条使下一次普通攻击成为秒杀。可以打断。' }, // '漫步冰海天使'
  14138: { detect: '视觉', grade: '简单', note: '读条直条' }, // '得到宽恕的不容忍'

  // 31-40层
  13977: { detect: undefined, grade: undefined, note: undefined }, // '得到宽恕的纯真'
  13978: { detect: undefined, grade: undefined, note: undefined }, // '得到宽恕的奉承'
  14139: { detect: undefined, grade: undefined, note: undefined }, // '漫步石兵'
  14140: { detect: undefined, grade: undefined, note: undefined }, // '得到宽恕的瘟疫'
  14141: { detect: undefined, grade: undefined, note: undefined }, // '得到宽恕的堕落'
  14142: { detect: undefined, grade: undefined, note: undefined }, // '得到宽恕的勒索'
  14143: { detect: undefined, grade: undefined, note: undefined }, // '得到宽恕的偏见'
  14144: { detect: undefined, grade: undefined, note: undefined }, // '得到宽恕的伪善'
  14145: { detect: undefined, grade: undefined, note: undefined }, // '得到宽恕的任性'
  14146: { detect: undefined, grade: undefined, note: undefined }, // '得到宽恕的嘲弄'
  14147: { detect: undefined, grade: undefined, note: undefined }, // '漫步异端审问官'
  14148: { detect: undefined, grade: undefined, note: undefined }, // '漫步鸟'
  14149: { detect: undefined, grade: undefined, note: undefined }, // '漫步石狮'
  14150: { detect: undefined, grade: undefined, note: undefined }, // '漫步亚克鲁斯'
  14151: { detect: undefined, grade: undefined, note: undefined }, // '漫步飞马'

  // 41-50层
  14152: { detect: undefined, grade: undefined, note: undefined }, // '漫步替身'
  14153: { detect: undefined, grade: undefined, note: undefined }, // '漫步托尔巴龟'
  14154: { detect: undefined, grade: undefined, note: undefined }, // '漫步水蚺'
  14155: { detect: undefined, grade: undefined, note: undefined }, // '漫步三裂'
  14156: { detect: undefined, grade: undefined, note: undefined }, // '漫步蜥蜴'
  14157: { detect: undefined, grade: undefined, note: undefined }, // '漫步白蚁'
  14158: { detect: undefined, grade: undefined, note: undefined }, // '漫步蚁狮'
  14159: { detect: undefined, grade: undefined, note: undefined }, // '漫步钳嘴鸟'
  14160: { detect: undefined, grade: undefined, note: undefined }, // '漫步壁崖飞鸢'
  14161: { detect: undefined, grade: undefined, note: undefined }, // '漫步武器'
  14162: { detect: undefined, grade: undefined, note: undefined }, // '漫步龙舌兰'
  14163: { detect: undefined, grade: undefined, note: undefined }, // '漫步发芽大口花'
  14164: { detect: undefined, grade: undefined, note: undefined }, // '漫步螳螂'
  14263: { detect: undefined, grade: undefined, note: undefined }, // '奥古布纳巴里'

  // 51-60层
  14097: { detect: undefined, grade: undefined, note: undefined }, // '元祖马利克刺人仙'
  14098: { detect: undefined, grade: undefined, note: undefined }, // '埃米尔仙人刺'
  14099: { detect: undefined, grade: undefined, note: undefined }, // '艾米拉仙人花'
  14165: { detect: undefined, grade: undefined, note: undefined }, // '漫步褐爪'
  14166: { detect: undefined, grade: undefined, note: undefined }, // '漫步守护者'
  14167: { detect: undefined, grade: undefined, note: undefined }, // '漫步沙蛇'
  14168: { detect: undefined, grade: undefined, note: undefined }, // '漫步美甲兽'
  14169: { detect: undefined, grade: undefined, note: undefined }, // '漫步巨蜥'
  14170: { detect: undefined, grade: undefined, note: undefined }, // '漫步邪恶海鸟'
  14171: { detect: undefined, grade: undefined, note: undefined }, // '漫步帕查玛玛'
  14172: { detect: undefined, grade: undefined, note: undefined }, // '漫步神香草'
  14173: { detect: undefined, grade: undefined, note: undefined }, // '漫步恐鹤'
  14174: { detect: undefined, grade: undefined, note: undefined }, // '漫步吼叫的小豹'
  14175: { detect: undefined, grade: undefined, note: undefined }, // '漫步狞猫'
  14176: { detect: undefined, grade: undefined, note: undefined }, // '漫步巨人'
  14177: { detect: undefined, grade: undefined, note: undefined }, // '漫步甲虫'

  // 61-70层
  13971: { detect: undefined, grade: undefined, note: undefined }, // '得到宽恕的狂热'
  14178: { detect: undefined, grade: undefined, note: undefined }, // '得到宽恕的暴动'
  14179: { detect: undefined, grade: undefined, note: undefined }, // '得到宽恕的争论'
  14180: { detect: undefined, grade: undefined, note: undefined }, // '漫步蜂后'
  14181: { detect: undefined, grade: undefined, note: undefined }, // '得到宽恕的怨恨'
  14182: { detect: undefined, grade: undefined, note: undefined }, // '漫步塔罗斯'
  14183: { detect: undefined, grade: undefined, note: undefined }, // '漫步壁崖鼹鼠'
  14184: { detect: undefined, grade: undefined, note: undefined }, // '得到宽恕的偏颇'
  14185: { detect: undefined, grade: undefined, note: undefined }, // '得到宽恕的恶作剧'
  14186: { detect: undefined, grade: undefined, note: undefined }, // '得到宽恕的贪食'
  14187: { detect: undefined, grade: undefined, note: undefined }, // '得到宽恕的疑虑'
  14188: { detect: undefined, grade: undefined, note: undefined }, // '得到宽恕的眷恋'
  14189: { detect: undefined, grade: undefined, note: undefined }, // '漫步诺姆'
  14190: { detect: undefined, grade: undefined, note: undefined }, // '漫步恩戈齐'

  // 71-80层
  13968: { detect: undefined, grade: undefined, note: undefined }, // '得到宽恕的亵渎'
  14191: { detect: undefined, grade: undefined, note: undefined }, // '得到宽恕的不和'
  14192: { detect: undefined, grade: undefined, note: undefined }, // '得到宽恕的腐化物'
  14193: { detect: undefined, grade: undefined, note: undefined }, // '得到宽恕的恶意'
  14194: { detect: undefined, grade: undefined, note: undefined }, // '漫步食岩者'
  14195: { detect: undefined, grade: undefined, note: undefined }, // '漫步爆岩怪'
  14196: { detect: undefined, grade: undefined, note: undefined }, // '漫步奶油泡芙'
  14197: { detect: undefined, grade: undefined, note: undefined }, // '得到宽恕的虚夸'
  14198: { detect: undefined, grade: undefined, note: undefined }, // '得到宽恕的傲慢'
  14199: { detect: undefined, grade: undefined, note: undefined }, // '得到宽恕的诽谤'
  14200: { detect: undefined, grade: undefined, note: undefined }, // '得到宽恕的不信任'
  14201: { detect: undefined, grade: undefined, note: undefined }, // '漫步阿米特'
  14202: { detect: undefined, grade: undefined, note: undefined }, // '漫步蠕虫'
  14203: { detect: undefined, grade: undefined, note: undefined }, // '漫步铰颌蚁'

  // 81-90层
  14090: { detect: undefined, grade: undefined, note: undefined }, // '玛拉科达'
  14204: { detect: undefined, grade: undefined, note: undefined }, // '漫步卡马'
  14205: { detect: undefined, grade: undefined, note: undefined }, // '被召唤的巴力'
  14206: { detect: undefined, grade: undefined, note: undefined }, // '漫步骑士'
  14207: { detect: undefined, grade: undefined, note: undefined }, // '被召唤的梦魔'
  14208: { detect: undefined, grade: undefined, note: undefined }, // '被召唤的洪巴巴'
  14209: { detect: undefined, grade: undefined, note: undefined }, // '被召唤的格雷姆林'
  14210: { detect: undefined, grade: undefined, note: undefined }, // '漫步异豺'
  14211: { detect: undefined, grade: undefined, note: undefined }, // '漫步卡部斯'
  14212: { detect: undefined, grade: undefined, note: undefined }, // '被召唤的小撒旦'
  14213: { detect: undefined, grade: undefined, note: undefined }, // '被召唤的上级恶魔'
  14214: { detect: undefined, grade: undefined, note: undefined }, // '被召唤的盖因'
  14215: { detect: undefined, grade: undefined, note: undefined }, // '被召唤的刻耳柏洛斯'
  14216: { detect: undefined, grade: undefined, note: undefined }, // '被召唤的行吟诗人'

  // 91-100层
  14037: { detect: undefined, grade: undefined, note: undefined }, // '至极悲痛'
  14038: { detect: undefined, grade: undefined, note: undefined }, // '被侵蚀的食罪灵'
  14217: { detect: undefined, grade: undefined, note: undefined }, // '漫步狼人'
  14218: { detect: undefined, grade: undefined, note: undefined }, // '被召唤的古辛'
  14219: { detect: undefined, grade: undefined, note: undefined }, // '被召唤的梦祸'
  14220: { detect: undefined, grade: undefined, note: undefined }, // '被召唤的单身汉'
  14221: { detect: undefined, grade: undefined, note: undefined }, // '被召唤的破坏本能'
  14222: { detect: undefined, grade: undefined, note: undefined }, // '被召唤的锯齿花'
  14223: { detect: undefined, grade: undefined, note: undefined }, // '漫步紫三裂'
  14224: { detect: undefined, grade: undefined, note: undefined }, // '漫步食人花'
  14225: { detect: undefined, grade: undefined, note: undefined }, // '被召唤的扎哈克'
  14226: { detect: undefined, grade: undefined, note: undefined }, // '被召唤的阿刻戎'
  14227: { detect: undefined, grade: undefined, note: undefined }, // '被召唤的傀儡'
  14228: { detect: undefined, grade: undefined, note: undefined }, // '漫步恶念'
  14229: { detect: undefined, grade: undefined, note: undefined }, // '被召唤的古恶魔'
} as const

export { PtEnemies, type EnemyData }
