interface XivApiJson {
  ActionCategory: ActionCategory
  ActionCategoryTarget: string
  ActionCategoryTargetID: number
  ActionCombo?: unknown
  ActionComboTarget: string
  ActionComboTargetID: number
  ActionProcStatus?: unknown
  ActionProcStatusTarget: string
  ActionProcStatusTargetID: number
  ActionTimelineHit: ActionTimelineHit
  ActionTimelineHitTarget: string
  ActionTimelineHitTargetID: number
  AdditionalCooldownGroup: number
  AffectsPosition: number
  AnimationEnd: AnimationEnd
  AnimationEndTarget: string
  AnimationEndTargetID: number
  AnimationStart?: unknown
  AnimationStartTarget: string
  AnimationStartTargetID: number
  Aspect: number
  AttackType?: unknown
  AttackTypeTarget: string
  AttackTypeTargetID: string
  BehaviourType: number
  CanTargetDead: number
  CanTargetFriendly: number
  CanTargetHostile: number
  CanTargetParty: number
  CanTargetSelf: number
  Cast100ms: number
  CastType: number
  ClassJob?: unknown
  ClassJobCategory: ClassJobCategory
  ClassJobCategoryTarget: string
  ClassJobCategoryTargetID: number
  ClassJobLevel: number
  ClassJobTarget: string
  ClassJobTargetID: string
  CooldownGroup: number
  Description: string
  DescriptionJSON: string[]
  DescriptionJSON_cn?: unknown
  DescriptionJSON_de: string[]
  DescriptionJSON_en: string[]
  DescriptionJSON_fr: string[]
  DescriptionJSON_ja: string[]
  DescriptionJSON_kr?: unknown
  Description_cn?: unknown
  Description_de: string
  Description_en: string
  Description_fr: string
  Description_ja: string
  Description_kr?: unknown
  EffectRange: number
  GameContentLinks: unknown[]
  GamePatch: GamePatch
  ID: number
  Icon: string
  IconHD: string
  IconID: number
  IsPlayerAction: number
  IsPvP: number
  IsRoleAction: number
  MaxCharges: number
  Name: string
  Name_de: string
  Name_en: string
  Name_fr: string
  Name_ja: string
  Omen?: unknown
  OmenTarget: string
  OmenTargetID: number
  Patch: number
  PreservesCombo: number
  PrimaryCostType: number
  PrimaryCostValue: number
  Range: number
  Recast100ms: number
  SecondaryCostType: number
  SecondaryCostValue: number
  StatusGainSelf?: unknown
  StatusGainSelfTarget: string
  StatusGainSelfTargetID: number
  TargetArea: number
  UnlockLink: number
  Url: string
  VFX?: unknown
  VFXTarget: string
  VFXTargetID: number
  XAxisModifier: number
}

interface GamePatch {
  Banner: string
  ExName: string
  ExVersion: number
  ID: number
  Name: string
  Name_cn: string
  Name_de: string
  Name_en: string
  Name_fr: string
  Name_ja: string
  Name_kr: string
  PatchNotes: string
  PatchNotes_de: string
  PatchNotes_en: string
  PatchNotes_fr: string
  PatchNotes_ja: string
  ReleaseDate: number
  Version: string
}

interface ClassJobCategory {
  ACN: number
  ADV: number
  ALC: number
  ARC: number
  ARM: number
  AST: number
  BLM: number
  BLU: number
  BRD: number
  BSM: number
  BTN: number
  CNJ: number
  CRP: number
  CUL: number
  DNC: number
  DRG: number
  DRK: number
  FSH: number
  GLA: number
  GNB: number
  GSM: number
  ID: number
  LNC: number
  LTW: number
  MCH: number
  MIN: number
  MNK: number
  MRD: number
  NIN: number
  Name: string
  Name_de: string
  Name_en: string
  Name_fr: string
  Name_ja: string
  PGL: number
  PLD: number
  RDM: number
  ROG: number
  RPR: number
  SAM: number
  SCH: number
  SGE: number
  SMN: number
  THM: number
  WAR: number
  WHM: number
  WVR: number
}

interface AnimationEnd {
  ActionTimelineIDMode: number
  ID: number
  IsLoop: number
  IsMotionCanceledByMoving: number
  Key: string
  Key_en: string
  KillUpper: number
  LoadType: number
  LookAtMode: number
  Pause: number
  Priority: number
  Resident: number
  ResidentPap: number
  Slot: number
  Stance: number
  StartAttach: number
  Type: number
  WeaponTimeline: WeaponTimeline
  WeaponTimelineTarget: string
  WeaponTimelineTargetID: number
}

interface WeaponTimeline {
  File: string
  File_en: string
  ID: number
  NextWeaponTimeline: string
}

interface ActionTimelineHit {
  ActionTimelineIDMode: number
  ID: number
  IsLoop: number
  IsMotionCanceledByMoving: number
  Key: string
  Key_en: string
  KillUpper: number
  LoadType: number
  LookAtMode: number
  Pause: number
  Priority: number
  Resident: number
  ResidentPap: number
  Slot: number
  Stance: number
  StartAttach: number
  Type: number
  WeaponTimeline?: unknown
  WeaponTimelineTarget: string
  WeaponTimelineTargetID: number
}

interface ActionCategory {
  ID: number
  Name: string
  Name_de: string
  Name_en: string
  Name_fr: string
  Name_ja: string
}
