import type { BisValue } from './bisUtils'
import { getRoleType } from './lootParser'

export interface BisPreset {
  name: string
  roleType: 'tank' | 'healer' | 'dps'
  specificRoles?: string[] // 例如 ['D1', 'D2']
  config: Record<string, BisValue>
}

// 在asvel的配装器，设置为“显示获取途径”，在书签中或者F12中运行以下JS即可提取对应格式Object。
// javascript:(function(){const slotMap={"武器":"weapon","头部":"head","身体":"body","手部":"hands","腿部":"legs","脚部":"feet","耳饰":"earring","项链":"necklace","手镯":"bracelet","戒指":"ring"};const jobName=document.querySelector(".condition_job-name")?.innerText.trim()||document.querySelector(".gears_job-name")?.innerText.trim()||document.querySelector(".mdc-top-app-bar__title")?.innerText.trim()||"未知职业";const getRoleType=(j)=>{if(/^(战士|绝枪战士|暗黑骑士|骑士)/.test(j))return"tank";if(/^(白魔法师|占星术士|学者|贤者)/.test(j))return"healer";return"dps"};const config={};const rings=[];const rows=document.querySelectorAll("tr.gears_item:not(.-food)");rows.forEach(tr=>{const slotText=tr.querySelector(".gears_inline-slot")?.innerText.trim();const nameText=tr.querySelector(".gears_name")?.innerText.trim();if(slotText==="戒指"){rings.push(nameText.includes("零式")?"raid":"tome");return}const id=slotMap[slotText];if(id&&nameText){config[id]=nameText.includes("零式")?"raid":"tome"}});if(rings.length>0){config.ring=rings.includes("raid")?"raid":"tome"}config.twine=1;config.coating=1;config.tome=config.weapon==="tome"?1:0;config.solvent=config.weapon==="tome"?1:0;const preset={name:"孤风行 - "+jobName,roleType:getRoleType(jobName),config:config};const json=JSON.stringify(preset,null,2).replace(/"(\w+)":/g,"$1:")+",";function copy(text){const t=document.createElement("textarea");t.value=text;document.body.appendChild(t);t.select();try{document.execCommand("copy");alert("提取成功！\n职业："+jobName+"\n戒指逻辑："+(config.ring==="raid"?"已设为零式":"已设为点数"))}catch(e){prompt("请手动复制：",text)}document.body.removeChild(t)}copy(json)})();
export const BIS_PRESETS: BisPreset[] = [
  {
    name: '孤风行 7.4 - 坦克通用',
    roleType: 'tank',
    config: {
      weapon: 'raid',
      head: 'raid',
      body: 'tome',
      hands: 'raid',
      legs: 'raid',
      feet: 'tome',
      earring: 'raid',
      necklace: 'tome',
      bracelet: 'tome',
      ring: 'raid',
      twine: 1,
      coating: 1,
      tome: 0,
      solvent: 0,
    },
  },
  {
    name: '孤风行 7.4 - 白贤2.42',
    roleType: 'healer',
    config: {
      weapon: 'raid',
      head: 'raid',
      body: 'tome',
      hands: 'raid',
      legs: 'raid',
      feet: 'raid',
      earring: 'tome',
      necklace: 'raid',
      bracelet: 'tome',
      ring: 'tome',
      twine: 1,
      coating: 1,
      tome: 0,
      solvent: 0,
    },
  },
  {
    name: '孤风行 7.4 - 白贤2.43',
    roleType: 'healer',
    config: {
      weapon: 'raid',
      head: 'raid',
      body: 'tome',
      hands: 'tome',
      legs: 'raid',
      feet: 'raid',
      earring: 'raid',
      necklace: 'raid',
      bracelet: 'tome',
      ring: 'tome',
      twine: 1,
      coating: 1,
      tome: 0,
      solvent: 0,
    },
  },
  {
    name: '孤风行 7.4 - 4奶通用',
    roleType: 'healer',
    config: {
      weapon: 'raid',
      head: 'raid',
      body: 'tome',
      hands: 'raid',
      legs: 'raid',
      feet: 'raid',
      earring: 'raid',
      necklace: 'raid',
      bracelet: 'tome',
      ring: 'tome',
      twine: 1,
      coating: 1,
      tome: 0,
      solvent: 0,
    },
  },
  {
    name: '孤风行 7.4 - 学者2.31',
    roleType: 'healer',
    specificRoles: ['H2'],
    config: {
      weapon: 'raid',
      head: 'raid',
      body: 'tome',
      hands: 'raid',
      legs: 'raid',
      feet: 'raid',
      earring: 'raid',
      necklace: 'raid',
      bracelet: 'tome',
      ring: 'tome',
      twine: 1,
      coating: 1,
      tome: 0,
      solvent: 0,
    },
  },
  {
    name: '孤风行 7.4 - 龙镰通用',
    roleType: 'dps',
    specificRoles: ['D1', 'D2'],
    config: {
      weapon: 'raid',
      head: 'tome',
      body: 'raid',
      hands: 'tome',
      legs: 'tome',
      feet: 'raid',
      earring: 'tome',
      necklace: 'tome',
      bracelet: 'raid',
      ring: 'raid',
      twine: 1,
      coating: 1,
      tome: 0,
      solvent: 0,
    },
  },
  {
    name: '孤风行 7.4 - 武僧1.94',
    roleType: 'dps',
    specificRoles: ['D1', 'D2'],
    config: {
      weapon: 'raid',
      head: 'raid',
      body: 'tome',
      hands: 'raid',
      legs: 'raid',
      feet: 'raid',
      earring: 'tome',
      necklace: 'tome',
      bracelet: 'raid',
      ring: 'raid',
      twine: 1,
      coating: 1,
      tome: 0,
      solvent: 0,
    },
  },
  {
    name: '孤风行 7.4 - 武僧1.94（兼容武士）',
    roleType: 'dps',
    specificRoles: ['D1', 'D2'],
    config: {
      weapon: 'raid',
      head: 'tome',
      body: 'tome',
      hands: 'raid',
      legs: 'raid',
      feet: 'raid',
      earring: 'tome',
      necklace: 'tome',
      bracelet: 'raid',
      ring: 'raid',
      twine: 1,
      coating: 1,
      tome: 0,
      solvent: 0,
    },
  },
  {
    name: '孤风行 7.4 - 武僧1.93',
    roleType: 'dps',
    specificRoles: ['D1', 'D2'],
    config: {
      weapon: 'raid',
      head: 'raid',
      body: 'tome',
      hands: 'raid',
      legs: 'raid',
      feet: 'raid',
      earring: 'tome',
      necklace: 'raid',
      bracelet: 'raid',
      ring: 'raid',
      twine: 1,
      coating: 1,
      tome: 0,
      solvent: 0,
    },
  },
  {
    name: '孤风行 7.4 - 武士2.14',
    roleType: 'dps',
    specificRoles: ['D1', 'D2'],
    config: {
      weapon: 'raid',
      head: 'raid',
      body: 'tome',
      hands: 'raid',
      legs: 'raid',
      feet: 'raid',
      earring: 'tome',
      necklace: 'tome',
      bracelet: 'raid',
      ring: 'raid',
      twine: 1,
      coating: 1,
      tome: 0,
      solvent: 0,
    },
  },
  {
    name: '孤风行 7.4 - 武士2.17',
    roleType: 'dps',
    specificRoles: ['D1', 'D2'],
    config: {
      weapon: 'raid',
      head: 'raid',
      body: 'tome',
      hands: 'raid',
      legs: 'raid',
      feet: 'tome',
      earring: 'tome',
      necklace: 'tome',
      bracelet: 'raid',
      ring: 'raid',
      twine: 1,
      coating: 1,
      tome: 0,
      solvent: 0,
    },
  },
  {
    name: '孤风行 7.4 - 蝰蛇剑士2.12',
    roleType: 'dps',
    specificRoles: ['D1', 'D2'],
    config: {
      weapon: 'raid',
      head: 'raid',
      body: 'tome',
      hands: 'tome',
      legs: 'raid',
      feet: 'tome',
      earring: 'raid',
      necklace: 'raid',
      bracelet: 'tome',
      ring: 'raid',
      twine: 1,
      coating: 1,
      tome: 0,
      solvent: 0,
    },
  },
  {
    name: '孤风行 7.4 - 蝰蛇剑士2.08（兼容忍者远敏）',
    roleType: 'dps',
    specificRoles: ['D1', 'D2'],
    config: {
      weapon: 'raid',
      head: 'raid',
      body: 'tome',
      hands: 'raid',
      legs: 'raid',
      feet: 'raid',
      earring: 'raid',
      necklace: 'raid',
      bracelet: 'tome',
      ring: 'raid',
      twine: 1,
      coating: 1,
      tome: 0,
      solvent: 0,
    },
  },
  {
    name: '孤风行 7.4 - 蝰蛇剑士2.08',
    roleType: 'dps',
    specificRoles: ['D1', 'D2'],
    config: {
      weapon: 'raid',
      head: 'raid',
      body: 'tome',
      hands: 'tome',
      legs: 'raid',
      feet: 'tome',
      earring: 'raid',
      necklace: 'raid',
      bracelet: 'tome',
      ring: 'raid',
      twine: 1,
      coating: 1,
      tome: 0,
      solvent: 0,
    },
  },
  {
    name: '孤风行 7.4 - 忍者',
    roleType: 'dps',
    specificRoles: ['D1', 'D2'],
    config: {
      weapon: 'raid',
      head: 'raid',
      body: 'tome',
      hands: 'tome',
      legs: 'raid',
      feet: 'tome',
      earring: 'raid',
      necklace: 'raid',
      bracelet: 'tome',
      ring: 'raid',
      twine: 1,
      coating: 1,
      tome: 0,
      solvent: 0,
    },
  },
  {
    name: '孤风行 7.4 - 远敏通用',
    roleType: 'dps',
    specificRoles: ['D3'],
    config: {
      weapon: 'raid',
      head: 'tome',
      body: 'raid',
      hands: 'raid',
      legs: 'tome',
      feet: 'tome',
      earring: 'raid',
      necklace: 'raid',
      bracelet: 'tome',
      ring: 'raid',
      twine: 1,
      coating: 1,
      tome: 0,
      solvent: 0,
    },
  },
  {
    name: '孤风行 7.4 - 诗舞最优',
    roleType: 'dps',
    specificRoles: ['D3'],
    config: {
      weapon: 'raid',
      head: 'tome',
      body: 'raid',
      hands: 'raid',
      legs: 'tome',
      feet: 'tome',
      earring: 'tome',
      necklace: 'raid',
      bracelet: 'tome',
      ring: 'raid',
      twine: 1,
      coating: 1,
      tome: 0,
      solvent: 0,
    },
  },
  {
    name: '孤风行 7.4 - 赤画2.50/黑魔2.45',
    roleType: 'dps',
    specificRoles: ['D4'],
    config: {
      weapon: 'raid',
      head: 'raid',
      body: 'raid',
      hands: 'raid',
      legs: 'tome',
      feet: 'tome',
      earring: 'raid',
      necklace: 'tome',
      bracelet: 'tome',
      ring: 'raid',
      twine: 1,
      coating: 1,
      tome: 0,
      solvent: 0,
    },
  },
  {
    name: '孤风行 7.4 - 赤画召2.48',
    roleType: 'dps',
    specificRoles: ['D4'],
    config: {
      weapon: 'raid',
      head: 'raid',
      body: 'raid',
      hands: 'raid',
      legs: 'tome',
      feet: 'tome',
      earring: 'raid',
      necklace: 'tome',
      bracelet: 'tome',
      ring: 'raid',
      twine: 1,
      coating: 1,
      tome: 0,
      solvent: 0,
    },
  },
  {
    name: '孤风行 7.4 - 黑魔法师2.17',
    roleType: 'dps',
    specificRoles: ['D4'],
    config: {
      weapon: 'raid',
      head: 'tome',
      body: 'tome',
      hands: 'tome',
      legs: 'raid',
      feet: 'raid',
      earring: 'tome',
      necklace: 'raid',
      bracelet: 'raid',
      ring: 'raid',
      twine: 1,
      coating: 1,
      tome: 0,
      solvent: 0,
    },
  },
]

export function getPresetsForRole(role: string | null | undefined): {
  recommended: BisPreset[]
  others: BisPreset[]
} {
  if (!role) return { recommended: [], others: [] }

  const roleType = getRoleType(role).replace('role-', '') as
    | 'tank'
    | 'healer'
    | 'dps'

  const allForRoleType = BIS_PRESETS.filter((p) => p.roleType === roleType)

  // 推荐：匹配特定位置的
  const recommended = allForRoleType.filter(
    (p) => p.specificRoles && p.specificRoles.includes(role),
  )

  // 其他：职能匹配但位置不匹配（或未指定位置）的
  const others = allForRoleType.filter(
    (p) => !p.specificRoles || !p.specificRoles.includes(role),
  )

  return { recommended, others }
}
