import fs from 'fs-extra'
import { readCsvRowsCached } from './csvCache'
import { csvPaths } from './paths'

type CsvRow = string[]

interface ActionMeta {
  name: string
  classJobLevel: number
}

function isMetaRow(row: CsvRow) {
  const first = (row[0] ?? '').toLowerCase()
  return ['key', '#', 'offset', 'int32'].includes(first)
}

function parseIntSafe(value: string | undefined) {
  const num = Number(value)
  if (!Number.isFinite(num))
    return 0
  return Math.trunc(num)
}

function normalizeLevel(level: number) {
  if (!Number.isFinite(level))
    return 1
  return Math.max(1, Math.trunc(level))
}

function getHeaderRow(rows: CsvRow[]) {
  return rows.find(row => (row[0] ?? '').toLowerCase() === '#') ?? []
}

function getColumnIndex(header: CsvRow, name: string) {
  return header.findIndex(col => (col ?? '').trim() === name)
}

function buildActionMetaMap(actionRows: CsvRow[]) {
  const header = getHeaderRow(actionRows)
  const nameIndex = getColumnIndex(header, 'Name')
  const classJobLevelIndex = getColumnIndex(header, 'ClassJobLevel')

  if (nameIndex < 0 || classJobLevelIndex < 0)
    throw new Error('Action.csv header changed: Name/ClassJobLevel not found.')

  const map = new Map<number, ActionMeta>()

  actionRows.forEach((row) => {
    if (isMetaRow(row))
      return
    const actionId = parseIntSafe(row[0])
    if (actionId <= 0)
      return
    map.set(actionId, {
      name: String(row[nameIndex] ?? '').trim(),
      classJobLevel: normalizeLevel(parseIntSafe(row[classJobLevelIndex])),
    })
  })

  return map
}

function buildUpgradeSteps(classJobActionUiRows: CsvRow[], actionMetaMap: Map<number, ActionMeta>) {
  const header = getHeaderRow(classJobActionUiRows)
  const baseActionIndex = getColumnIndex(header, 'BaseAction')
  const upgradeActionIndex = getColumnIndex(header, 'UpgradeAction')

  if (baseActionIndex < 0 || upgradeActionIndex < 0)
    throw new Error('ClassJobActionUI.csv header changed: BaseAction/UpgradeAction not found.')

  const groupedByBase = new Map<number, Set<number>>()

  classJobActionUiRows.forEach((row) => {
    if (isMetaRow(row))
      return
    const baseActionId = parseIntSafe(row[baseActionIndex])
    const upgradeActionId = parseIntSafe(row[upgradeActionIndex])
    if (baseActionId <= 0 || upgradeActionId <= 0 || baseActionId === upgradeActionId)
      return

    if (!groupedByBase.has(baseActionId))
      groupedByBase.set(baseActionId, new Set<number>())
    groupedByBase.get(baseActionId)!.add(upgradeActionId)
  })

  const stepMap = new Map<number, number>()

  groupedByBase.forEach((upgradeIds, baseActionId) => {
    const chain = [baseActionId, ...upgradeIds]
    chain.sort((a, b) => {
      const levelA = actionMetaMap.get(a)?.classJobLevel ?? 1
      const levelB = actionMetaMap.get(b)?.classJobLevel ?? 1
      if (levelA !== levelB)
        return levelA - levelB
      return a - b
    })

    for (let i = 0; i < chain.length - 1; i += 1) {
      const lower = chain[i]!
      const upper = chain[i + 1]!
      if (lower === upper)
        continue

      const existing = stepMap.get(lower)
      if (existing !== undefined && existing !== upper) {
        const existingLevel = actionMetaMap.get(existing)?.classJobLevel ?? 1
        const newLevel = actionMetaMap.get(upper)?.classJobLevel ?? 1
        if (newLevel < existingLevel || (newLevel === existingLevel && upper < existing))
          stepMap.set(lower, upper)
        continue
      }

      stepMap.set(lower, upper)
    }
  })

  const sortedEntries = [...stepMap.entries()].sort((a, b) => a[0] - b[0])
  const result: Record<number, number> = {}
  sortedEntries.forEach(([lower, upper]) => {
    result[lower] = upper
  })
  return result
}

function writeOutput(steps: Record<number, number>, actionMetaMap: Map<number, ActionMeta>) {
  const sortedIds = Object.keys(steps).map(v => Number(v)).sort((a, b) => a - b)
  const lines: string[] = []

  lines.push('// Generated by scripts/actionUpgradeStepsBake.ts')
  lines.push('// Source: chs/Action.csv + chs/ClassJobActionUI.csv')
  lines.push('export const BAKED_ACTION_UPGRADE_STEPS: Record<number, number> = {')

  sortedIds.forEach((lower) => {
    const upper = steps[lower]!
    const lowerName = actionMetaMap.get(lower)?.name || ''
    const upperName = actionMetaMap.get(upper)?.name || ''
    lines.push(`  ${lower}: ${upper}, // ${lowerName} -> ${upperName}`)
  })

  lines.push('}')
  lines.push('')

  fs.outputFileSync('src/resources/bakedActionUpgradeSteps.ts', lines.join('\n'), 'utf8')
}

async function main() {
  const actionRows = await readCsvRowsCached(`${csvPaths.cn}Action.csv`)
  const classJobActionUiRows = await readCsvRowsCached(`${csvPaths.cn}ClassJobActionUI.csv`)

  const actionMetaMap = buildActionMetaMap(actionRows)
  const steps = buildUpgradeSteps(classJobActionUiRows, actionMetaMap)
  writeOutput(steps, actionMetaMap)
}

await main()
