import fs from 'fs-extra'
import { readCsvRowsCached } from './csvCache'
import { csvPaths } from './paths'

const SKIP_ROW_KEYS = new Set(['key', '#', 'offset', 'int32', '0'])

const ATTACK_TYPE_NAME_OVERRIDES: Record<string, string> = {
  斬: '斩击',
  ブレス: '吐息',
  リミットブレイク: '极限技',
}

function parseIdToNameMap(rows: string[][]): Record<string, string> {
  const map: Record<string, string> = {}
  for (const row of rows) {
    const id = row[0]?.trim() ?? ''
    if (!id || SKIP_ROW_KEYS.has(id.toLowerCase()))
      continue
    map[id] = row[1] ?? ''
  }
  return map
}

function applyNameOverrides(map: Record<string, string>, overrides: Record<string, string>) {
  for (const key in map) {
    const current = map[key] ?? ''
    map[key] = overrides[current] ?? current
  }
}

function sortNumericKeyMap(map: Record<string, string>): Record<string, string> {
  return Object.fromEntries(
    Object.entries(map)
      .sort((a, b) => Number(a[0]) - Number(b[0])),
  )
}

function serializeMapConst(name: string, map: Record<string, string>): string {
  const lines = Object.entries(map).map(([key, value]) => `  ${key}: ${JSON.stringify(value)},`)
  return `export const ${name}: Record<string, string> = {\n${lines.join('\n')}\n}\n`
}

const actionCategoryRows = await readCsvRowsCached(`${csvPaths.cn}ActionCategory.csv`)
const attackTypeRows = await readCsvRowsCached(`${csvPaths.cn}AttackType.csv`)

const actionCategoryMap = sortNumericKeyMap(parseIdToNameMap(actionCategoryRows))
const attackTypeMap = sortNumericKeyMap(parseIdToNameMap(attackTypeRows))
applyNameOverrides(attackTypeMap, ATTACK_TYPE_NAME_OVERRIDES)

const output = `/* eslint-disable style/quotes */\n// AUTO-GENERATED by scripts/actionCategory.ts. DO NOT EDIT.\n\n${
  serializeMapConst('ActionCategoryTargetMap', actionCategoryMap)
}\n${
  serializeMapConst('AttackTypeTargetMap', attackTypeMap)
}`

fs.outputFileSync('src/resources/generated/actionCategory.ts', output)
