import fs from 'fs-extra'
import action2ClassJobLevelMapRaw from '../src/resources/generated/action2ClassJobLevel.json'
import { ACTION_UPGRADE_STEPS } from '../src/utils/compareSaveAction'
import { readCsvRowsCached } from './csvCache'
import { csvPaths } from './paths'

type CsvRow = string[]

interface BakedActionMetaLite {
  name: string
  icon: number
  classJob: number
  classJobCategory: number
  actionCategory: number
  recast100ms: number
  maxCharges: number
  classJobLevel: number
  isRoleAction: boolean
}

function isMetaRow(row: CsvRow) {
  const first = (row[0] ?? '').toLowerCase()
  return ['key', '#', 'offset', 'int32'].includes(first)
}

function parseBool(value: string | undefined) {
  if (!value)
    return false
  const normalized = value.trim().toLowerCase()
  return normalized === 'true' || normalized === '1'
}

function parseIntSafe(value: string | undefined) {
  const num = Number(value)
  if (!Number.isFinite(num))
    return 0
  return Math.trunc(num)
}

function getColumnIndex(header: CsvRow, name: string) {
  return header.findIndex(col => (col ?? '').trim() === name)
}

function getHeaderRow(rows: CsvRow[]) {
  return rows.find(row => (row[0] ?? '').toLowerCase() === '#') ?? []
}

function collectTargetActionIds() {
  const set = new Set<number>()

  Object.keys(action2ClassJobLevelMapRaw as Record<string, string>).forEach((id) => {
    const actionId = parseIntSafe(id)
    if (actionId > 0)
      set.add(actionId)
  })

  Object.entries(ACTION_UPGRADE_STEPS).forEach(([rawLower, rawUpper]) => {
    const lower = parseIntSafe(rawLower)
    const upper = Number(rawUpper)
    if (lower > 0)
      set.add(lower)
    if (Number.isFinite(upper) && upper > 0)
      set.add(Math.trunc(upper))
  })

  return set
}

function writeOutput(map: Record<number, BakedActionMetaLite>) {
  const ids = Object.keys(map).map(v => Number(v)).sort((a, b) => a - b)
  const lines: string[] = []
  lines.push('/* eslint-disable style/quotes */')
  lines.push('// Generated by scripts/actionMetaBake.ts')
  lines.push('// Source: chs/Action.csv + action2ClassJobLevel.json + ACTION_UPGRADE_STEPS')
  lines.push('')
  lines.push('export interface BakedActionMetaLite {')
  lines.push('  name: string')
  lines.push('  icon: number')
  lines.push('  classJob: number')
  lines.push('  classJobCategory: number')
  lines.push('  actionCategory: number')
  lines.push('  recast100ms: number')
  lines.push('  maxCharges: number')
  lines.push('  classJobLevel: number')
  lines.push('  isRoleAction: boolean')
  lines.push('}')
  lines.push('')
  lines.push('type BakedActionMetaLiteTuple = [')
  lines.push('  name: string,')
  lines.push('  icon: number,')
  lines.push('  classJob: number,')
  lines.push('  classJobCategory: number,')
  lines.push('  actionCategory: number,')
  lines.push('  recast100ms: number,')
  lines.push('  maxCharges: number,')
  lines.push('  classJobLevel: number,')
  lines.push('  isRoleAction: 0 | 1,')
  lines.push(']')
  lines.push('')
  lines.push('const RAW_BAKED_ACTION_META_LITE_BY_ID: Record<number, BakedActionMetaLiteTuple> = {')
  ids.forEach((id) => {
    const row = map[id]!
    const escapedName = JSON.stringify(row.name)
    lines.push(`  ${id}: [${escapedName}, ${row.icon}, ${row.classJob}, ${row.classJobCategory}, ${row.actionCategory}, ${row.recast100ms}, ${row.maxCharges}, ${row.classJobLevel}, ${row.isRoleAction ? 1 : 0}],`)
  })
  lines.push('}')
  lines.push('')
  lines.push('export const BAKED_ACTION_META_LITE_BY_ID: Record<number, BakedActionMetaLite> = {}')
  lines.push('Object.entries(RAW_BAKED_ACTION_META_LITE_BY_ID).forEach(([rawId, row]) => {')
  lines.push('  const id = Number(rawId)')
  lines.push('  if (!Number.isFinite(id) || id <= 0)')
  lines.push('    return')
  lines.push('  BAKED_ACTION_META_LITE_BY_ID[id] = {')
  lines.push('    name: row[0],')
  lines.push('    icon: row[1],')
  lines.push('    classJob: row[2],')
  lines.push('    classJobCategory: row[3],')
  lines.push('    actionCategory: row[4],')
  lines.push('    recast100ms: row[5],')
  lines.push('    maxCharges: row[6],')
  lines.push('    classJobLevel: row[7],')
  lines.push('    isRoleAction: row[8] > 0,')
  lines.push('  }')
  lines.push('})')
  lines.push('')
  fs.outputFileSync('src/resources/generated/bakedActionMetaLite.ts', lines.join('\n'), 'utf8')
}

async function main() {
  const actionRows = await readCsvRowsCached(`${csvPaths.cn}Action.csv`)
  const header = getHeaderRow(actionRows)

  const indexName = getColumnIndex(header, 'Name')
  const indexIcon = getColumnIndex(header, 'Icon')
  const indexClassJob = getColumnIndex(header, 'ClassJob')
  const indexClassJobCategory = getColumnIndex(header, 'ClassJobCategory')
  const indexActionCategory = getColumnIndex(header, 'ActionCategory')
  const indexRecast100ms = getColumnIndex(header, 'Recast100ms')
  const indexMaxCharges = getColumnIndex(header, 'MaxCharges')
  const indexClassJobLevel = getColumnIndex(header, 'ClassJobLevel')
  const indexIsRoleAction = getColumnIndex(header, 'IsRoleAction')

  if (
    indexName < 0
    || indexIcon < 0
    || indexClassJob < 0
    || indexClassJobCategory < 0
    || indexActionCategory < 0
    || indexRecast100ms < 0
    || indexMaxCharges < 0
    || indexClassJobLevel < 0
    || indexIsRoleAction < 0
  ) {
    throw new Error('Action.csv header changed: required columns not found.')
  }

  const targetActionIds = collectTargetActionIds()
  const map: Record<number, BakedActionMetaLite> = {}

  actionRows.forEach((row) => {
    if (isMetaRow(row))
      return
    const actionId = parseIntSafe(row[0])
    if (actionId <= 0 || !targetActionIds.has(actionId))
      return
    map[actionId] = {
      name: String(row[indexName] ?? '').trim(),
      icon: parseIntSafe(row[indexIcon]),
      classJob: parseIntSafe(row[indexClassJob]),
      classJobCategory: parseIntSafe(row[indexClassJobCategory]),
      actionCategory: parseIntSafe(row[indexActionCategory]),
      recast100ms: parseIntSafe(row[indexRecast100ms]),
      maxCharges: parseIntSafe(row[indexMaxCharges]),
      classJobLevel: parseIntSafe(row[indexClassJobLevel]),
      isRoleAction: parseBool(row[indexIsRoleAction]),
    }
  })

  writeOutput(map)
}

await main()
