import csv from 'csv-parser'
import fs from 'fs-extra'
import iconv from 'iconv-lite'
import action2ClassJobLevelMapRaw from '../src/resources/action2ClassJobLevel.json'
import { ACTION_UPGRADE_STEPS } from '../src/utils/compareSaveAction'
import { csvPaths } from './paths'

type CsvRow = string[]

interface BakedActionMetaLite {
  name: string
  icon: number
  classJob: number
  classJobCategory: number
  actionCategory: number
  recast100ms: number
  maxCharges: number
  classJobLevel: number
  isRoleAction: boolean
}

function isMetaRow(row: CsvRow) {
  const first = (row[0] ?? '').toLowerCase()
  return ['key', '#', 'offset', 'int32'].includes(first)
}

function parseBool(value: string | undefined) {
  if (!value)
    return false
  const normalized = value.trim().toLowerCase()
  return normalized === 'true' || normalized === '1'
}

function parseIntSafe(value: string | undefined) {
  const num = Number(value)
  if (!Number.isFinite(num))
    return 0
  return Math.trunc(num)
}

function getColumnIndex(header: CsvRow, name: string) {
  return header.findIndex(col => (col ?? '').trim() === name)
}

function getHeaderRow(rows: CsvRow[]) {
  return rows.find(row => (row[0] ?? '').toLowerCase() === '#') ?? []
}

async function readCsvRows(filePath: string) {
  const rows: CsvRow[] = []
  await new Promise<void>((resolve, reject) => {
    fs.createReadStream(filePath)
      .pipe(iconv.decodeStream('utf8'))
      .pipe(csv({ headers: false }))
      .on('data', (row: Record<string, string>) => {
        rows.push(Object.values(row))
      })
      .on('end', resolve)
      .on('error', reject)
  })
  return rows
}

function collectTargetActionIds() {
  const set = new Set<number>()

  Object.keys(action2ClassJobLevelMapRaw as Record<string, string>).forEach((id) => {
    const actionId = parseIntSafe(id)
    if (actionId > 0)
      set.add(actionId)
  })

  Object.entries(ACTION_UPGRADE_STEPS).forEach(([rawLower, rawUpper]) => {
    const lower = parseIntSafe(rawLower)
    const upper = Number(rawUpper)
    if (lower > 0)
      set.add(lower)
    if (Number.isFinite(upper) && upper > 0)
      set.add(Math.trunc(upper))
  })

  return set
}

function writeOutput(map: Record<number, BakedActionMetaLite>) {
  const ids = Object.keys(map).map(v => Number(v)).sort((a, b) => a - b)
  const lines: string[] = []
  lines.push('// Generated by scripts/actionMetaBake.ts')
  lines.push('// Source: chs/Action.csv + action2ClassJobLevel.json + ACTION_UPGRADE_STEPS')
  lines.push('')
  lines.push('export interface BakedActionMetaLite {')
  lines.push('  name: string')
  lines.push('  icon: number')
  lines.push('  classJob: number')
  lines.push('  classJobCategory: number')
  lines.push('  actionCategory: number')
  lines.push('  recast100ms: number')
  lines.push('  maxCharges: number')
  lines.push('  classJobLevel: number')
  lines.push('  isRoleAction: boolean')
  lines.push('}')
  lines.push('')
  lines.push('export const BAKED_ACTION_META_LITE_BY_ID: Record<number, BakedActionMetaLite> = {')
  ids.forEach((id) => {
    const row = map[id]!
    const escapedName = JSON.stringify(row.name)
    lines.push(`  ${id}: { name: ${escapedName}, icon: ${row.icon}, classJob: ${row.classJob}, classJobCategory: ${row.classJobCategory}, actionCategory: ${row.actionCategory}, recast100ms: ${row.recast100ms}, maxCharges: ${row.maxCharges}, classJobLevel: ${row.classJobLevel}, isRoleAction: ${row.isRoleAction} },`)
  })
  lines.push('}')
  lines.push('')
  fs.outputFileSync('src/resources/bakedActionMetaLite.ts', lines.join('\n'), 'utf8')
}

async function main() {
  const actionRows = await readCsvRows(`${csvPaths.cn}Action.csv`)
  const header = getHeaderRow(actionRows)

  const indexName = getColumnIndex(header, 'Name')
  const indexIcon = getColumnIndex(header, 'Icon')
  const indexClassJob = getColumnIndex(header, 'ClassJob')
  const indexClassJobCategory = getColumnIndex(header, 'ClassJobCategory')
  const indexActionCategory = getColumnIndex(header, 'ActionCategory')
  const indexRecast100ms = getColumnIndex(header, 'Recast100ms')
  const indexMaxCharges = getColumnIndex(header, 'MaxCharges')
  const indexClassJobLevel = getColumnIndex(header, 'ClassJobLevel')
  const indexIsRoleAction = getColumnIndex(header, 'IsRoleAction')

  if (
    indexName < 0
    || indexIcon < 0
    || indexClassJob < 0
    || indexClassJobCategory < 0
    || indexActionCategory < 0
    || indexRecast100ms < 0
    || indexMaxCharges < 0
    || indexClassJobLevel < 0
    || indexIsRoleAction < 0
  ) {
    throw new Error('Action.csv header changed: required columns not found.')
  }

  const targetActionIds = collectTargetActionIds()
  const map: Record<number, BakedActionMetaLite> = {}

  actionRows.forEach((row) => {
    if (isMetaRow(row))
      return
    const actionId = parseIntSafe(row[0])
    if (actionId <= 0 || !targetActionIds.has(actionId))
      return
    map[actionId] = {
      name: String(row[indexName] ?? '').trim(),
      icon: parseIntSafe(row[indexIcon]),
      classJob: parseIntSafe(row[indexClassJob]),
      classJobCategory: parseIntSafe(row[indexClassJobCategory]),
      actionCategory: parseIntSafe(row[indexActionCategory]),
      recast100ms: parseIntSafe(row[indexRecast100ms]),
      maxCharges: parseIntSafe(row[indexMaxCharges]),
      classJobLevel: parseIntSafe(row[indexClassJobLevel]),
      isRoleAction: parseBool(row[indexIsRoleAction]),
    }
  })

  writeOutput(map)
}

await main()
