import fs from 'fs-extra'
import action2ClassJobLevelMapRaw from '../src/resources/generated/action2ClassJobLevel.json'
import { ACTION_UPGRADE_STEPS } from '../src/utils/compareSaveAction'
import { readCsvRowsCached } from './csvCache'
import { csvPaths } from './paths'

type CsvRow = string[]

function isMetaRow(row: CsvRow) {
  const first = (row[0] ?? '').toLowerCase()
  return ['key', '#', 'offset', 'int32'].includes(first)
}

function parseBool(value: string | undefined) {
  if (!value)
    return false
  const normalized = value.trim().toLowerCase()
  return normalized === 'true' || normalized === '1'
}

function parseIntSafe(value: string | undefined) {
  const num = Number(value)
  if (!Number.isFinite(num))
    return 0
  return Math.trunc(num)
}

function getHeaderRow(rows: CsvRow[]) {
  return rows.find(row => (row[0] ?? '').toLowerCase() === '#') ?? []
}

function getColumnIndex(header: CsvRow, name: string) {
  return header.findIndex(col => (col ?? '').trim() === name)
}

function normalizeLevel(level: unknown, fallback = 1) {
  const num = Number(level)
  if (!Number.isFinite(num))
    return Math.max(1, Math.trunc(fallback))
  return Math.max(1, Math.trunc(num))
}

async function collectRoleActionIds() {
  const actionRows = await readCsvRowsCached(`${csvPaths.cn}Action.csv`)
  const header = getHeaderRow(actionRows)
  const isRoleActionIndex = getColumnIndex(header, 'IsRoleAction')
  const isPvPIndex = getColumnIndex(header, 'IsPvP')

  if (isRoleActionIndex < 0 || isPvPIndex < 0)
    throw new Error('Action.csv header changed: IsRoleAction/IsPvP not found.')

  const roleActionIds = new Set<number>()
  actionRows.forEach((row) => {
    if (isMetaRow(row))
      return
    if (!parseBool(row[isRoleActionIndex]))
      return
    if (parseBool(row[isPvPIndex]))
      return
    const actionId = parseIntSafe(row[0])
    if (actionId > 0)
      roleActionIds.add(actionId)
  })
  return [...roleActionIds].sort((a, b) => a - b)
}

function buildUpgradeChainMinLevelMap(roleActionIds: number[]) {
  const roleActionSet = new Set(roleActionIds)
  const action2ClassJobLevelMap = new Map<string, string>(
    Object.entries(action2ClassJobLevelMapRaw as Record<string, string>),
  )

  function getBaseLevel(actionId: number) {
    if (roleActionSet.has(actionId))
      return 1
    const fromMap = Number(action2ClassJobLevelMap.get(String(actionId)))
    if (Number.isFinite(fromMap) && fromMap > 0)
      return normalizeLevel(fromMap)
    return 1
  }

  const undirected = new Map<number, Set<number>>()
  Object.entries(ACTION_UPGRADE_STEPS).forEach(([rawLower, rawUpper]) => {
    const lower = Number(rawLower)
    const upper = Number(rawUpper)
    if (!Number.isFinite(lower) || lower <= 0 || !Number.isFinite(upper) || upper <= 0)
      return
    if (!undirected.has(lower))
      undirected.set(lower, new Set<number>())
    if (!undirected.has(upper))
      undirected.set(upper, new Set<number>())
    undirected.get(lower)!.add(upper)
    undirected.get(upper)!.add(lower)
  })

  const visited = new Set<number>()
  const result: Record<number, number> = {}

  for (const start of undirected.keys()) {
    if (visited.has(start))
      continue
    const stack = [start]
    const family: number[] = []
    while (stack.length > 0) {
      const current = stack.pop()!
      if (visited.has(current))
        continue
      visited.add(current)
      family.push(current)
      const next = undirected.get(current)
      if (!next)
        continue
      next.forEach((id) => {
        if (!visited.has(id))
          stack.push(id)
      })
    }

    const familyMinLevel = family.reduce((min, id) => Math.min(min, getBaseLevel(id)), Number.POSITIVE_INFINITY)
    family.forEach((id) => {
      result[id] = familyMinLevel
    })
  }

  return result
}

function writeUpgradeChainMinLevelMap(map: Record<number, number>) {
  const sortedIds = Object.keys(map).map(v => Number(v)).sort((a, b) => a - b)
  const lines: string[] = []
  lines.push('// Generated by scripts/actionMinLevelBake.ts')
  lines.push('// Source: action2ClassJobLevel.json + ACTION_UPGRADE_STEPS')
  lines.push('export const BAKED_UPGRADE_CHAIN_MIN_LEVEL_BY_ACTION_ID: Record<number, number> = {')
  sortedIds.forEach((id) => {
    lines.push(`  ${id}: ${map[id]},`)
  })
  lines.push('}')
  lines.push('')
  fs.outputFileSync('src/resources/generated/bakedUpgradeChainMinLevel.ts', lines.join('\n'), 'utf8')
}

async function main() {
  const roleActionIds = await collectRoleActionIds()
  const upgradeChainMinLevelMap = buildUpgradeChainMinLevelMap(roleActionIds)
  writeUpgradeChainMinLevelMap(upgradeChainMinLevelMap)
}

await main()
