import csv from 'csv-parser'
import fs from 'fs-extra'
import iconv from 'iconv-lite'
import { csvPaths } from './paths'

type CsvRow = string[]

function isMetaRow(row: CsvRow) {
  const first = (row[0] ?? '').toLowerCase()
  return ['key', '#', 'offset', 'int32'].includes(first)
}

function parseBool(value: string | undefined) {
  if (!value)
    return false
  return value.trim().toLowerCase() === 'true'
}

function parseIntSafe(value: string | undefined) {
  const num = Number(value)
  if (!Number.isFinite(num))
    return 0
  return Math.trunc(num)
}

async function readCsvRows(filePath: string) {
  const rows: CsvRow[] = []
  await new Promise<void>((resolve, reject) => {
    fs.createReadStream(filePath)
      .pipe(iconv.decodeStream('utf8'))
      .pipe(csv({ headers: false }))
      .on('data', (row: Record<string, string>) => {
        rows.push(Object.values(row))
      })
      .on('end', resolve)
      .on('error', reject)
  })
  return rows
}

function getHeaderRow(rows: CsvRow[]) {
  return rows.find(row => (row[0] ?? '').toLowerCase() === '#') ?? []
}

function getColumnIndex(header: CsvRow, name: string) {
  return header.findIndex(col => (col ?? '').trim() === name)
}

async function main() {
  const classJobRows = await readCsvRows(`${csvPaths.cn}ClassJob.csv`)
  const classJobCategoryRows = await readCsvRows(`${csvPaths.cn}ClassJobCategory.csv`)
  const actionRows = await readCsvRows(`${csvPaths.cn}Action.csv`)

  const classJobHeader = getHeaderRow(classJobRows)
  const classJobCategoryHeader = getHeaderRow(classJobCategoryRows)
  const actionHeader = getHeaderRow(actionRows)

  const classJobAbbrIndex = getColumnIndex(classJobHeader, 'Abbreviation')
  const actionIsRoleIndex = getColumnIndex(actionHeader, 'IsRoleAction')
  const actionIsPvPIndex = getColumnIndex(actionHeader, 'IsPvP')
  const actionClassJobCategoryIndex = getColumnIndex(actionHeader, 'ClassJobCategory')

  if (classJobAbbrIndex < 0 || actionIsRoleIndex < 0 || actionIsPvPIndex < 0 || actionClassJobCategoryIndex < 0) {
    throw new Error('CSV header changed: required columns not found.')
  }

  // Abbreviation -> ClassJob ID
  const jobIdByAbbr = new Map<string, number>()
  classJobRows.forEach((row) => {
    if (isMetaRow(row))
      return
    const id = parseIntSafe(row[0])
    const abbr = (row[classJobAbbrIndex] ?? '').trim()
    if (id > 0 && abbr)
      jobIdByAbbr.set(abbr, id)
  })

  // ClassJobCategory column index -> ClassJob ID
  const categoryColumnToJobId = new Map<number, number>()
  classJobCategoryHeader.forEach((col, index) => {
    const abbr = (col ?? '').trim()
    const jobId = jobIdByAbbr.get(abbr)
    if (jobId)
      categoryColumnToJobId.set(index, jobId)
  })

  // Collect all categories referenced by non-PvP role actions.
  const roleCategoryIds = new Set<number>()
  actionRows.forEach((row) => {
    if (isMetaRow(row))
      return
    if (!parseBool(row[actionIsRoleIndex]))
      return
    if (parseBool(row[actionIsPvPIndex]))
      return
    const categoryId = parseIntSafe(row[actionClassJobCategoryIndex])
    if (categoryId > 0)
      roleCategoryIds.add(categoryId)
  })

  // categoryId -> set(jobId)
  const categoryToJobs = new Map<number, Set<number>>()
  classJobCategoryRows.forEach((row) => {
    if (isMetaRow(row))
      return
    const categoryId = parseIntSafe(row[0])
    if (!roleCategoryIds.has(categoryId))
      return
    const jobs = new Set<number>()
    categoryColumnToJobId.forEach((jobId, colIndex) => {
      if (parseBool(row[colIndex]))
        jobs.add(jobId)
    })
    categoryToJobs.set(categoryId, jobs)
  })

  // jobId -> category IDs
  const map: Record<number, number[]> = {}
  categoryToJobs.forEach((jobs, categoryId) => {
    jobs.forEach((jobId) => {
      if (!map[jobId])
        map[jobId] = []
      map[jobId]!.push(categoryId)
    })
  })

  Object.keys(map).forEach((jobId) => {
    map[Number(jobId)] = Array.from(new Set(map[Number(jobId)])).sort((a, b) => a - b)
  })

  const sortedJobIds = Object.keys(map).map(v => Number(v)).sort((a, b) => a - b)
  const lines: string[] = []
  lines.push('// Generated by scripts/roleActionCategoryByJob.ts')
  lines.push('// Source: chs/Action.csv + ClassJob.csv + ClassJobCategory.csv')
  lines.push('export const ROLE_ACTION_CATEGORY_BY_JOB: Record<number, number[]> = {')
  sortedJobIds.forEach((jobId) => {
    lines.push(`  ${jobId}: [${map[jobId]!.join(', ')}],`)
  })
  lines.push('}')
  lines.push('')

  const output = `${lines.join('\n')}`
  const outPath = 'src/resources/roleActionCategoryByJob.ts'
  fs.outputFileSync(outPath, output, 'utf8')
  console.log(`[roleActionCategoryByJob] generated ${outPath} with ${sortedJobIds.length} jobs.`)
}

await main()
