import fs from 'fs-extra'
import { readCsvRowsCached } from './csvCache.js'
import { csvPaths } from './paths.js'

const worlds: Set<string> = new Set()
const rows = await readCsvRowsCached(`${csvPaths.cn}World.csv`)
rows.forEach((row, index) => {
  if (index <= 4)
    return
  if (row[2])
    worlds.add(row[2])
})

const worldsArray = Array.from(worlds)
const worldsString = `/* eslint-disable style/quotes */\n// Generated by scripts/world.ts\n// Source: chs/World.csv\nexport const worlds = ${JSON.stringify(worldsArray, null, 2)};\n`
const outputPath = 'src/resources/generated/worlds.ts'

fs.outputFileSync(outputPath, worldsString)
