// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    FflogsImport: typeof import('./components/timeline/fflogsImport.vue')['default']
    TimelineShow: typeof import('./components/timeline/timelineShow.vue')['default']
    UnlockedText: typeof import('./components/unlockedText.vue')['default']
  }
}

export { }
