name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "*.md"
    types:
      - opened
      - synchronize
      - reopened

permissions:
  pages: write
  id-token: write
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Update Submodules & Patch
        run: bash scripts/update-cactbot.sh

      - name: Install Vite+
        run: |
          curl -fsSL https://vite.plus | bash
          echo "$HOME/.vite-plus/bin" >> $GITHUB_PATH

      - name: Install Node.js
        run: vp env pin lts && vp env install

      - name: Install Dependencies
        run: vp install

      - name: Build
        run: vp build

      - name: Deploy to GitHub Pages
        if: github.event_name != 'pull_request'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
