name: Lint

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "*.md"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Vite+
        run: |
          curl -fsSL https://vite.plus | bash
          echo "$HOME/.vite-plus/bin" >> $GITHUB_PATH

      - name: Install Node.js
        run: vp env pin lts && vp env install

      - name: Install Dependencies
        run: vp install

      - name: Apply Patches
        run: bash scripts/update-cactbot.sh

      - name: Lint
        run: vp check
